name: get-water-level

on:
  schedule: 
    # runs every hour
    # - cron: '0 * * * *'
    - cron: '0/10 * * * *'
    
jobs:
  fetch-data:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install packages
        run: |
          R -e 'install.packages("xml2")'
          R -e 'install.packages("purrr")'
          R -e 'install.packages("dplyr")'
      
      # Run R script to fetch data from endpoint
      - name: Fetch result
        if: always()
        run: Rscript R/fetch-data.R
        
      - name: Combine datasets
        if: always()
        run: Rscript R/merge-data.R

      - name: Commit files
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git add data/*
          git commit -am "Data fetch for $(date)"
          git push origin main
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions
      